version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
      python: 3.11
  pre_build:
    commands:
    - cd ./source
    - npm ci
    - cd ..
  build:
    commands:
    - export POETRY_HOME=/opt/poetry
    - python3 -m venv $POETRY_HOME
    - $POETRY_HOME/bin/pip install poetry==2.1.2
    - $POETRY_HOME/bin/poetry --version
    - $POETRY_HOME/bin/pip install poetry-plugin-export==1.9.0
    - cd ./deployment
    - ./build-s3-dist.sh -b $DIST_OUTPUT_BUCKET -v $VERSION
    - ./build-open-source-dist.sh
    - cd ..
  post_build:
    commands:
    - cd ./deployment
    - export AWS_DEFAULT_REGION=us-east-1
    - ./run-unit-tests.sh
    - cd ..
artifacts:
  files:
  - '**/*'
