# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
description: |
 ### Document Name - ASR-AFSBP_1.0.0_S3.13

 ## What does this document do?
  This document sets an example lifecycle policy that transfers objects greater than 10 GB to S3 Intelligent Tiering after 90 days. 
  It is recommended to set lifecycle policies appropriate for the objects stored in your S3 bucket.

 ## Input Parameters
 * Finding: (Required) Security Hub finding details JSON
 * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.

 ## Output Parameters
 * Remediation.Output - Remediation results

 ## Documentation Links
 * [AWS FSBP v1.0.0 S3.13](https://docs.aws.amazon.com/securityhub/latest/userguide/s3-controls.html#s3-13)

schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
outputs:
  - ParseInput.AffectedObject
  - Remediation.Output
parameters:
  Finding:
    type: StringMap
    description: The input from the Orchestrator Step function for the S3.13 finding
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'
  RemediationRoleName:
    type: String
    default: "%%ROLE=SO0111-SetS3LifecyclePolicy%%"
    allowedPattern: '^[\w+=,.@-]+$'

mainSteps:
  -
    name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: BucketName
        Selector: $.Payload.resource_id
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
      - Name: SecHubInputParams
        Selector: $.Payload.input_params
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: '^arn:(?:aws|aws-cn|aws-us-gov):s3:::([A-Za-z0-9.-]{3,63})$'
        expected_control_id: [ 'S3.13' ]
      Runtime: python3.11
      Handler: parse_event
      Script: |-
        %%SCRIPT=common/parse_input.py%%
  - name: GetInputParams
    action: 'aws:executeScript'
    outputs:
      - Name: targetTransitionDays
        Selector: $.Payload.targetTransitionDays
        Type: Integer
      - Name: targetExpirationDays
        Selector: $.Payload.targetExpirationDays
        Type: Integer
      - Name: targetTransitionStorageClass
        Selector: $.Payload.targetTransitionStorageClass
        Type: String
    inputs:
      InputPayload:
        SecHubInputParams: '{{ParseInput.SecHubInputParams}}'
        DefaultParams: {
          "targetTransitionDays": 30,
          "targetExpirationDays": 0,
          "targetTransitionStorageClass": "INTELLIGENT_TIERING"
        }
        expected_control_id: [ 'S3.13' ]
      Runtime: python3.11
      Handler: get_input_params
      Script: |-
        %%SCRIPT=common/get_input_params.py%%

  - name: Remediation
    action: 'aws:executeAutomation'
    isEnd: false
    inputs:
      DocumentName: ASR-SetS3LifecyclePolicy
      RuntimeParameters:
        BucketName: '{{ParseInput.BucketName}}'
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/{{RemediationRoleName}}'
        TargetTransitionDays: '{{GetInputParams.targetTransitionDays}}'
        TargetExpirationDays: '{{GetInputParams.targetExpirationDays}}'
        TargetTransitionStorageClass: '{{GetInputParams.targetTransitionStorageClass}}'

  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Set example lifecycle policy for {{ParseInput.BucketName}}'
        UpdatedBy: 'ASR-AFSBP_1.0.0_S3.13'
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true
