# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
description: |
  ### Document Name - ASR-AFSBP_1.0.0_ECS.5
  
  ## What does this document do?
  This document triggers the ECS.5 (ASR-LimitECSRootFilesystemAccess) remediation runbook.
  
  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  * RemediationRoleName: (Optional) The name of the role that allows Automation to remediate the finding on your behalf.
  
  ## Output Parameters
  * Remediation.Output
  
  ## Documentation Links
  * [AWS AFSBP v1.0.0 ECS.5](https://docs.aws.amazon.com/securityhub/latest/userguide/ecs-controls.html#ecs-5)
schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'
  Finding:
    type: StringMap
    description: The input from the Orchestrator Step function for the ECS.5 finding
  RemediationRoleName:
    type: 'String'
    default: '%%ROLE=SO0111-LimitECSRootFilesystemAccess%%'
    allowedPattern: '^[\w+=,.@-]+$'

outputs:
  - ParseInput.AffectedObject
  - Remediation.Output

mainSteps:
  - name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: TaskDefinitionId
        Selector: $.Payload.resource_id
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
      - Name: RemediationRegion
        Selector: $.Payload.resource_region
        Type: String
      - Name: RemediationAccount
        Selector: $.Payload.account_id
        Type: String
      - Name: SecHubInputParams
        Selector: $.Payload.input_params
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: '^arn:(?:aws|aws-cn|aws-us-gov):ecs:(?:[a-z]{2}(?:-gov)?-[a-z]+-\d):\d{12}:task-definition/([a-zA-Z0-9_-]{1,255}:\d)$'
        expected_control_id:
          - 'ECS.5'
      Runtime: python3.11
      Handler: parse_event
      Script: |-
        %%SCRIPT=common/parse_input.py%%
    isEnd: false
  -
    name: Remediation
    action: 'aws:executeAutomation'
    inputs:
      DocumentName: ASR-LimitECSRootFilesystemAccess
      TargetLocations:
        - Accounts: [ '{{ParseInput.RemediationAccount}}' ]
          Regions: [ '{{ParseInput.RemediationRegion}}' ]
          ExecutionRoleName: '{{ RemediationRoleName }}'
      RuntimeParameters:
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/{{RemediationRoleName}}'
        TaskDefinitionId: '{{ParseInput.TaskDefinitionId}}'
  -
    name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
        - Id: '{{ParseInput.FindingId}}'
          ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Created new revision for task definition {{ParseInput.TaskDefinitionId}}'
        UpdatedBy: 'ASR-AFSBP_1.0.0_ECS.5'
      Workflow:
        Status: RESOLVED
    description: Update finding
