# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
description: |
  ### Document Name - ASR-AFSBP_1.0.0_EC2.18
 
  ## What does this document do?
  This document revokes inbound security group rules that allow unrestricted access to ports that are not authorized.
  Authorized ports are listed in authorizedTcpPorts and authorizedUdpPorts parameters.
 
  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  * RemediationRoleName: (Optional) The name of the role that allows Automation to remediate the finding on your behalf.
 
  ## Output Parameters
  * Remediation.Output
 
  ## Documentation Links
  * [AWS FSBP v1.0.0 EC2.18](https://docs.aws.amazon.com/securityhub/latest/userguide/ec2-controls.html#ec2-18)
schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'
  Finding:
    type: StringMap
    description: The input from the Orchestrator Step function for the EC2.18 finding
  RemediationRoleName:
    type: 'String'
    default: '%%ROLE=SO0111-RevokeUnauthorizedInboundRules%%'
    allowedPattern: '^[\w+=,.@-]+$'

outputs:
  - ParseInput.AffectedObject
  - Remediation.Output
 
mainSteps:
  - name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: FindingId
        Selector: $.Payload.finding.Id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.finding.ProductArn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
      - Name: SecurityGroupId
        Selector: $.Payload.resource_id
        Type: String
      - Name: RemediationRegion
        Selector: $.Payload.resource_region
        Type: String
      - Name: RemediationAccount
        Selector: $.Payload.account_id
        Type: String
      - Name: SecHubInputParams
        Selector: $.Payload.input_params
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: '^arn:(?:aws|aws-cn|aws-us-gov):ec2:(?:[a-z]{2}(?:-gov)?-[a-z]+-\d):\d{12}:security-group/(sg-[0-9a-f]*)$'
        expected_control_id: 
          - 'EC2.18'
      Runtime: python3.11
      Handler: parse_event
      Script: |-
        %%SCRIPT=common/parse_input.py%%
  
  - name: GetInputParams
    action: 'aws:executeScript'
    outputs:
      - Name: authorizedUdpPorts
        Selector: $.Payload.authorizedUdpPorts
        Type: StringList
      - Name: authorizedTcpPorts
        Selector: $.Payload.authorizedTcpPorts
        Type: StringList
    inputs:
      InputPayload:
        SecHubInputParams: '{{ParseInput.SecHubInputParams}}'
        DefaultParams: {
          "authorizedTcpPorts": [ "80", "443" ],
          "authorizedUdpPorts": [],
        }
        expected_control_id: [ 'EC2.18' ]
      Runtime: python3.11
      Handler: get_input_params
      Script: |-
        %%SCRIPT=common/get_input_params.py%%

  - name: Remediation
    action: 'aws:executeAutomation'
    inputs:
      DocumentName: ASR-RevokeUnauthorizedInboundRules
      TargetLocations:
        - Accounts: [ '{{ParseInput.RemediationAccount}}' ]
          Regions: [ '{{ParseInput.RemediationRegion}}' ]
          ExecutionRoleName: '{{ RemediationRoleName }}'
      RuntimeParameters:
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/{{RemediationRoleName}}'
        SecurityGroupId: '{{ParseInput.SecurityGroupId}}'
        AuthorizedTcpPorts: '{{GetInputParams.authorizedTcpPorts}}'
        AuthorizedUdpPorts: '{{GetInputParams.authorizedUdpPorts}}'

  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Revoked unrestricted inbound security group rules on unauthorized ports.'
        UpdatedBy: 'ASR-AFSBP_1.0.0_EC2.18'
      Workflow:
        Status: RESOLVED
    description: Update finding