description: |
  ### Document Name - SHARR-PCI_3.2.1_CloudTrail.1
  ## What does this document do?
  This document enables SSE KMS encryption for log files using the SHARR remediation KMS CMK
  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  ## Output Parameters
  * Remediation.Output - Output from the remediation

  ## Documentation Links
  * [PCI CloudTrail.1](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-pci-controls.html#pcidss-cloudtrail-1)

schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
outputs:
  - Remediation.Output
  - ParseInput.AffectedObject
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+'
  Finding:
    type: StringMap
    description: The input from Step function for the finding
  KMSKeyArn:
    type: String
    default: >-
      {{ssm:/Solutions/SO0111/CMK_REMEDIATION_ARN}}

mainSteps:
  - 
    name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
      - Name: TrailArn
        Selector: $.Payload.resource_id
        Type: String
      - Name: TrailRegion
        Selector: $.Payload.details.AwsCloudTrailTrail.HomeRegion
        Type: String
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: ''
        expected_control_id: 'PCI.CloudTrail.1'
      Runtime: python3.7
      Handler: parse_event
      Script: |-
        %%SCRIPT=pci_parse_input.py%%
    isEnd: false

  - 
    name: Remediation
    action: 'aws:executeAutomation'
    inputs:
      DocumentName: SHARR-EnableCloudTrailEncryption
      RuntimeParameters:
        TrailRegion: '{{ParseInput.TrailRegion}}'
        TrailArn: '{{ParseInput.TrailArn}}'
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-EnableCloudTrailEncryption_{{global:REGION}}'
        KMSKeyArn: '{{KMSKeyArn}}'
    isEnd: false

  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
        - Id: '{{ParseInput.FindingId}}'
          ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: Encryption enabled on CloudTrail
        UpdatedBy: SHARR-PCI_3.2.1_CloudTrail.1
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true