// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import * as cdk from 'aws-cdk-lib';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Table } from 'aws-cdk-lib/aws-dynamodb';
import * as iam from 'aws-cdk-lib/aws-iam';
import { PolicyStatement } from 'aws-cdk-lib/aws-iam';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as wafv2 from 'aws-cdk-lib/aws-wafv2';
import { Construct } from 'constructs';
import { addCfnGuardSuppression } from '../cdk-helper/add-cfn-guard-suppression';
import { createLogGroup } from '../cdk-helper/log-group';
import { getLambdaCode } from '../cdk-helper/lambda-code-manifest';
import { CDKConfig, getConfig } from '../config/cdk-config';
import { ApiLambdaEnvironmentConfig } from '@asr/data-models';
import { RouteDefinition, SENSITIVE_WRITE_ROUTES } from '../../lambdas/api/rateLimiting/routeTiers';

export interface ApiConstructProps {
  solutionId: string;
  solutionVersion: string;
  solutionTMN: string;
  solutionsBucket: s3.IBucket;
  resourceNamePrefix: string;
  findingsTable: string;
  remediationHistoryTable: string;
  remediationConfigTable: Table;
  resourceFiltersTable: Table;
  userAccountMappingTable: Table;
  functionName: string;
  kmsKeyARN: string;
  authorizer?: apigateway.CognitoUserPoolsAuthorizer;
  userPoolId?: string;
  orchestratorArn: string;
  distributionDomainName: string;
  csvExportBucket: s3.IBucket;
  presignedUrlTTLDays: number;
  securityHubV2Enabled: string;
  notificationConfigTable: dynamodb.Table;
  notificationBatchesTable: dynamodb.Table;
  iacTemplatesBucket: s3.IBucket;
  adminNotificationTopic: sns.ITopic;
}

/**
 * Managed-rule-group rules that block legitimate machine-to-machine (M2M)
 * callers and so are downgraded to Count. M2M clients authenticate with the
 * Cognito `client_credentials` flow (no browser), so by design they present a
 * non-browser User-Agent and originate from cloud/hosting IP ranges — exactly
 * the traffic these rules target. They sit IN FRONT OF the Cognito authorizer,
 * so a valid full-access token cannot rescue the request; the rule fires first
 * and returns 403 before authorization runs.
 *
 * Count (not removed) keeps the detection signal in WAF metrics/logs while
 * ceasing to block. All other rules in these groups — and the AnonymousIpList /
 * AmazonIpReputationList groups, which catch VPN/Tor/proxy and known-bad IPs —
 * stay at their Block default, so the browser-facing WebUI surface is unchanged.
 *
 * Keyed by managed group name → rule names to downgrade.
 */
const M2M_COUNT_RULE_OVERRIDES: Record<string, string[]> = {
  AWSManagedRulesBotControlRuleSet: [
    // 'This category can include API requests.' — AWS Bot Control rule reference.
    'SignalNonBrowserUserAgent',
    // Cloud/datacenter source IPs — where M2M clients run.
    'SignalKnownBotDataCenter',
    // 'requests generated by bots from the HTTP libraries of various programming
    // languages... may include API requests.' This is the rule that fires on real
    // M2M callers (curl, the AWS SDKs, requests/axios) — confirmed via WAF sampled
    // requests against a live deployment. Without this override the other two are
    // insufficient and HTTP-library clients still get a 403.
    'CategoryHttpLibrary',
  ],
};

/**
 * Key of the custom response body the rate-based rules return with HTTP 429.
 * Registered in the Web ACL's `customResponseBodies` and referenced by each
 * rate-based rule's block action.
 */
const RATE_LIMIT_RESPONSE_BODY_KEY = 'ASRRateLimited';

/**
 * `Access-Control-Allow-Headers` value for the WAF rate-limit 429 response.
 * Must match the API's CORS configuration (the `allowHeaders` list and the
 * CORSResponse GatewayResponses in the construct below) so a browser can read
 * the 429 that WAF returns ahead of API Gateway.
 */
const RATE_LIMIT_CORS_ALLOW_HEADERS =
  'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent';

/**
 * Builds a Web ACL rule that references an AWS-managed rule group, with the group
 * set to `overrideAction: none` so every rule keeps its own default action.
 *
 * `ruleActionOverrides` downgrades the named rules (e.g. to Count) surgically,
 * per-rule, without changing the group-wide `overrideAction`.
 */
function managedRuleGroupRule(
  managedGroupName: string,
  vendorName: string,
  priority: number,
  ruleActionOverrides?: wafv2.CfnWebACL.RuleActionOverrideProperty[],
): wafv2.CfnWebACL.RuleProperty {
  return {
    name: `${vendorName}-${managedGroupName}`,
    priority,
    overrideAction: { none: {} },
    statement: {
      managedRuleGroupStatement: {
        name: managedGroupName,
        vendorName,
        ...(ruleActionOverrides && { ruleActionOverrides }),
      },
    },
    visibilityConfig: {
      cloudWatchMetricsEnabled: true,
      metricName: managedGroupName,
      sampledRequestsEnabled: true,
    },
  };
}

/**
 * Builds the WAF rate-based rules that enforce per-user and per-IP rate limiting for the API.
 *
 * Coarse, defense-in-depth backstop: WAF's minimum granularity is 10 requests
 * per 60s per aggregation instance, so these rules bound abusive bursts but
 * cannot enforce a precise per-second limit. Per-user rules aggregate on the
 * Cognito JWT in the Authorization header; requests missing that header are
 * omitted by WAF and are instead covered by the per-IP rule. The rule action
 * follows `wafConfig.mode` (default 'block', so over-limit requests get a 429
 * with a custom JSON body); switch to 'count' to confirm the exact inspected
 * UriPath via WAF sampled requests without enforcing.
 *
 * `apiStageName` is the first URI path segment WAF inspects (e.g. '/prod/...'),
 * so scope-down path matches must be built from the same value used for the
 * API Gateway stage.
 */
function buildRateLimitRules(
  wafConfig: CDKConfig['rateLimiting']['waf'],
  apiStageName: string,
  resourceNamePrefix: string,
): wafv2.CfnWebACL.RuleProperty[] {
  // WAF's default block action returns 403. Override it to 429 Too Many Requests
  // so a rate-limited caller gets the correct, actionable status. The body is
  // registered under RATE_LIMIT_RESPONSE_BODY_KEY on the Web ACL.
  //
  // WAF is evaluated in front of API Gateway, so a blocked request never reaches
  // the CORSResponse4xx/5xx GatewayResponses below. Without CORS headers on the
  // WAF response the browser web UI would see an opaque network error instead of
  // the 429, so mirror the API's CORS headers here. Keep in sync with the
  // GatewayResponse headers (`responseHeaders`) and `allowHeaders` below.
  const corsResponseHeaders: wafv2.CfnWebACL.CustomHTTPHeaderProperty[] = [
    { name: 'Access-Control-Allow-Origin', value: '*' },
    { name: 'Access-Control-Allow-Headers', value: RATE_LIMIT_CORS_ALLOW_HEADERS },
    { name: 'Access-Control-Allow-Methods', value: 'GET,OPTIONS,POST,PUT,DELETE' },
  ];
  const rateLimitAction: wafv2.CfnWebACL.RuleActionProperty =
    wafConfig.mode === 'block'
      ? {
          block: {
            customResponse: {
              responseCode: 429,
              customResponseBodyKey: RATE_LIMIT_RESPONSE_BODY_KEY,
              responseHeaders: corsResponseHeaders,
            },
          },
        }
      : { count: {} };

  const noneTransform: wafv2.CfnWebACL.TextTransformationProperty[] = [{ priority: 0, type: 'NONE' }];
  // URL-decode then canonicalize the path before matching so encoded variants
  // (e.g. /prod/notif%69cations) or traversal/slash tricks (e.g. //prod/, /./)
  // cannot evade the literal scope-down match.
  const pathTransform: wafv2.CfnWebACL.TextTransformationProperty[] = [
    { priority: 0, type: 'URL_DECODE' },
    { priority: 1, type: 'NORMALIZE_PATH' },
  ];
  const authHeaderKey: wafv2.CfnWebACL.RateBasedStatementCustomKeyProperty = {
    header: { name: 'authorization', textTransformations: noneTransform },
  };

  const uriPathMatch = (
    searchString: string,
    positionalConstraint: 'EXACTLY' | 'STARTS_WITH',
  ): wafv2.CfnWebACL.StatementProperty => ({
    byteMatchStatement: {
      fieldToMatch: { uriPath: {} },
      positionalConstraint,
      searchString,
      textTransformations: pathTransform,
    },
  });

  const methodMatch = (method: string): wafv2.CfnWebACL.StatementProperty => ({
    byteMatchStatement: {
      fieldToMatch: { method: {} },
      positionalConstraint: 'EXACTLY',
      searchString: method,
      textTransformations: noneTransform,
    },
  });

  // Build the sensitive-write scope-down directly from the route tier map
  // (SENSITIVE_WRITE_ROUTES = the `critical` + `sensitiveWrite` tiers in
  // source/lambdas/api/rateLimiting/routeTiers.ts) so the WAF rule cannot drift
  // from the canonical tiers. Each route contributes a (method AND path)
  // statement and the rule matches the OR of them. Because method and path are
  // AND'd per route, a mutating `read`-tier route that shares a prefix (e.g.
  // POST /notifications/{id}/test) is never swept into the sensitive-write limit.
  const routeMatchStatement = (route: RouteDefinition): wafv2.CfnWebACL.StatementProperty => {
    const paramIndex = route.pathTemplate.indexOf('/{');
    const pathStatement =
      paramIndex === -1
        ? // No path params: match the exact resource path.
          uriPathMatch(`/${apiStageName}${route.pathTemplate}`, 'EXACTLY')
        : // Trailing path param: match the literal prefix up to and including the
          // slash before the param, scoped to this method so deeper sub-paths
          // under a different method/tier are not matched.
          uriPathMatch(`/${apiStageName}${route.pathTemplate.slice(0, paramIndex + 1)}`, 'STARTS_WITH');
    return { andStatement: { statements: [methodMatch(route.method), pathStatement] } };
  };

  const sensitiveWriteRouteStatements: wafv2.CfnWebACL.StatementProperty[] =
    SENSITIVE_WRITE_ROUTES.map(routeMatchStatement);

  return [
    {
      // Tight per-user limit on mutating requests to sensitive resource paths
      // (control bulk-edit, filters, users, finding actions, notifications).
      name: 'ASRSensitiveWriteRateLimit',
      priority: 8,
      action: rateLimitAction,
      statement: {
        rateBasedStatement: {
          limit: wafConfig.sensitiveWriteLimit,
          evaluationWindowSec: wafConfig.evaluationWindowSec,
          aggregateKeyType: 'CUSTOM_KEYS',
          customKeys: [authHeaderKey],
          scopeDownStatement: {
            orStatement: { statements: sensitiveWriteRouteStatements },
          },
        },
      },
      visibilityConfig: {
        cloudWatchMetricsEnabled: true,
        metricName: `${resourceNamePrefix}ASRSensitiveWriteRateLimit`,
        sampledRequestsEnabled: true,
      },
    },
    {
      // Broad per-user backstop across all endpoints (e.g. rapid paginated
      // reads attempting bulk data exfiltration with a single token).
      name: 'ASRPerUserRateLimit',
      priority: 9,
      action: rateLimitAction,
      statement: {
        rateBasedStatement: {
          limit: wafConfig.perUserLimit,
          evaluationWindowSec: wafConfig.evaluationWindowSec,
          aggregateKeyType: 'CUSTOM_KEYS',
          customKeys: [authHeaderKey],
        },
      },
      visibilityConfig: {
        cloudWatchMetricsEnabled: true,
        metricName: `${resourceNamePrefix}ASRPerUserRateLimit`,
        sampledRequestsEnabled: true,
      },
    },
    {
      // Per-source-IP catch-all, including unauthenticated floods that the
      // header-keyed rules omit.
      name: 'ASRPerIpRateLimit',
      priority: 10,
      action: rateLimitAction,
      statement: {
        rateBasedStatement: {
          limit: wafConfig.perIpLimit,
          evaluationWindowSec: wafConfig.evaluationWindowSec,
          aggregateKeyType: 'IP',
        },
      },
      visibilityConfig: {
        cloudWatchMetricsEnabled: true,
        metricName: `${resourceNamePrefix}ASRPerIpRateLimit`,
        sampledRequestsEnabled: true,
      },
    },
  ];
}

export class ApiConstruct extends Construct {
  public readonly api: apigateway.RestApi;
  public readonly apiLambda: lambda.Function;

  constructor(scope: Construct, id: string, props: ApiConstructProps) {
    super(scope, id);
    const stack = cdk.Stack.of(this);
    const config = getConfig();

    this.apiLambda = new lambda.Function(this, 'APILambda', {
      runtime: lambda.Runtime.NODEJS_24_X,
      functionName: props.functionName,
      logGroup: createLogGroup(this, 'APILambdaLogGroup'),
      handler: 'api/handlers/apiHandler.handler',
      code: getLambdaCode(props.solutionsBucket, props.solutionTMN, props.solutionVersion, 'asr_lambdas.zip'),
      description: 'ASR API Lambda function',
      environment: {
        SOLUTION_ID: props.solutionId,
        SOLUTION_VERSION: props.solutionVersion,
        SOLUTION_TRADEMARKEDNAME: props.solutionTMN,
        POWERTOOLS_LOG_LEVEL: 'INFO',
        USER_POOL_ID: props.userPoolId ?? '',
        USER_ACCOUNT_MAPPING_TABLE_NAME: props.userAccountMappingTable.tableName,
        FINDINGS_TABLE_NAME: cdk.Fn.select(1, cdk.Fn.split('/', props.findingsTable)),
        REMEDIATION_HISTORY_TABLE_NAME: cdk.Fn.select(1, cdk.Fn.split('/', props.remediationHistoryTable)),
        REMEDIATION_CONFIG_TABLE_NAME: props.remediationConfigTable.tableName,
        RESOURCE_FILTERS_TABLE_NAME: props.resourceFiltersTable.tableName,
        CSV_EXPORT_BUCKET_NAME: props.csvExportBucket.bucketName,
        PRESIGNED_URL_TTL_DAYS: props.presignedUrlTTLDays.toString(),
        ORCHESTRATOR_ARN: props.orchestratorArn,
        WEB_UI_URL: `https://${props.distributionDomainName}`,
        AWS_ACCOUNT_ID: stack.account,
        STACK_ID: stack.stackId,
        SECURITY_HUB_V2_ENABLED: props.securityHubV2Enabled,
        EXPORT_MAX_TIME_MS: String(config.export.maxTimeMs), // API Gateway has 29s hard limit; 26s for export + 3s buffer
        EXPORT_MAX_RECORDS: String(config.export.maxRecords), // Memory safety limit
        NOTIFICATION_CONFIG_TABLE_NAME: props.notificationConfigTable.tableName,
        NOTIFICATION_BATCHES_TABLE_NAME: props.notificationBatchesTable.tableName,
        AWS_PARTITION: stack.partition,
        RESOURCE_NAME_PREFIX: props.resourceNamePrefix,
        IAC_TEMPLATES_BUCKET: props.iacTemplatesBucket.bucketName,
        ADMIN_NOTIFICATION_TOPIC_ARN: props.adminNotificationTopic.topicArn,
      } satisfies ApiLambdaEnvironmentConfig,
      memorySize: 512,
      timeout: cdk.Duration.seconds(29), // Match API Gateway timeout (29s hard limit)
      tracing: lambda.Tracing.ACTIVE,
    });

    const findingsTable = dynamodb.Table.fromTableArn(this, 'FindingsTable', props.findingsTable);
    findingsTable.grantReadWriteData(this.apiLambda);

    const remediationHistoryTable = dynamodb.Table.fromTableArn(
      this,
      'RemediationHistoryTable',
      props.remediationHistoryTable,
    );
    remediationHistoryTable.grantReadWriteData(this.apiLambda);

    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['dynamodb:Query'],
        resources: [`${props.findingsTable}/index/*`],
      }),
    );

    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['dynamodb:Query'],
        resources: [`${props.remediationHistoryTable}/index/*`],
      }),
    );

    props.userAccountMappingTable.grantReadWriteData(this.apiLambda);

    props.remediationConfigTable.grantReadWriteData(this.apiLambda);

    props.resourceFiltersTable.grantReadWriteData(this.apiLambda);

    props.notificationConfigTable.grantReadWriteData(this.apiLambda);

    // Write access for reconciliation tasks created when enforcement settings change
    props.notificationBatchesTable.grantWriteData(this.apiLambda);

    this.apiLambda.addToRolePolicy(
      new PolicyStatement({
        actions: ['ssm:GetParameter', 'ssm:GetParameters', 'ssm:PutParameter', 'ssm:DeleteParameter'],
        resources: [`arn:${stack.partition}:ssm:*:${stack.account}:parameter/Solutions/SO0111/*`],
      }),
    );

    if (props.userPoolId) {
      this.apiLambda.addToRolePolicy(
        new iam.PolicyStatement({
          effect: iam.Effect.ALLOW,
          actions: [
            'cognito-idp:GetUser',
            'cognito-idp:AdminListGroupsForUser',
            'cognito-idp:AdminGetUser',
            'cognito-idp:ListUsers',
            'cognito-idp:AdminCreateUser',
            'cognito-idp:AdminAddUserToGroup',
            'cognito-idp:AdminDeleteUser',
          ],
          resources: [
            `arn:${stack.partition}:cognito-idp:${stack.region}:${stack.account}:userpool/${props.userPoolId}`,
          ],
        }),
      );
    }

    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['kms:Decrypt', 'kms:DescribeKey'],
        resources: [props.kmsKeyARN],
      }),
    );

    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['states:StartExecution'],
        resources: [props.orchestratorArn],
      }),
    );

    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3:PutObject', 's3:GetObject'],
        resources: [`${props.csvExportBucket.bucketArn}/*`],
      }),
    );

    // Grant permissions for email recipient resolution
    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['organizations:DescribeAccount'],
        resources: ['*'],
      }),
    );
    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['account:GetAlternateContact'],
        resources: [`arn:${stack.partition}:account::${stack.account}:account`],
      }),
    );

    // SNS topic lifecycle management for per-config email notification topics
    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: [
          'sns:CreateTopic',
          'sns:DeleteTopic',
          'sns:TagResource',
          'sns:Subscribe',
          'sns:Unsubscribe',
          'sns:ListSubscriptionsByTopic',
        ],
        resources: [`arn:${stack.partition}:sns:${stack.region}:${stack.account}:asr-notifications-*`],
      }),
    );

    // SNS publish for ASR-managed email topics and customer-owned SNS channel topics.
    // Customer topics use arbitrary ARNs stored in notification configs, so we cannot
    // scope beyond same-account + same-region (validated at runtime in sns-channel.ts).
    // This mirrors the pattern used by the channel fanout Lambda.
    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['sns:Publish'],
        resources: [`arn:${stack.partition}:sns:${stack.region}:${stack.account}:*`],
      }),
    );

    // Publishing to a KMS-encrypted (SSE) SNS topic also requires kms:GenerateDataKey + kms:Decrypt
    // on the topic's key. Customer SNS channel topics can use arbitrary customer-managed keys unknown
    // at deploy time, so the key ARN cannot be enumerated; the grant is scoped to same-account +
    // same-region keys and constrained to use through SNS only via the kms:ViaService condition.
    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['kms:GenerateDataKey', 'kms:Decrypt'],
        resources: [`arn:${stack.partition}:kms:${stack.region}:${stack.account}:key/*`],
        conditions: {
          StringEquals: { 'kms:ViaService': `sns.${stack.region}.amazonaws.com` },
        },
      }),
    );

    // Publish to the dedicated admin security notifications topic. grantPublish adds the
    // scoped sns:Publish plus the kms:GenerateDataKey*/Decrypt grant required to publish to
    // the CMK-encrypted topic (the wildcard sns:Publish above does not cover KMS).
    props.adminNotificationTopic.grantPublish(this.apiLambda);

    // Secrets Manager read for channel credential validation (test notification delivery)
    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['secretsmanager:GetSecretValue'],
        resources: [
          `arn:${stack.partition}:secretsmanager:${stack.region}:${stack.account}:secret:${config.notificationChannels.secretsResourcePattern}*`,
        ],
      }),
    );

    // S3 read permission for IaC templates bucket (test notification delivery).
    // Use explicit statements rather than bucket.grantRead: the bucket is
    // encrypted with the solution CMK in the parent stack, and grantRead would
    // mutate that key's resource policy from this nested stack, creating a
    // parent<->nested cyclic dependency. KMS decrypt on the CMK is already
    // granted above (kms:Decrypt on props.kmsKeyARN), mirroring the CSV bucket.
    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3:GetObject'],
        resources: [`${props.iacTemplatesBucket.bucketArn}/*`],
      }),
    );
    this.apiLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3:ListBucket'],
        resources: [props.iacTemplatesBucket.bucketArn],
      }),
    );

    const lambdaResource = this.apiLambda.node.findChild('Resource') as lambda.CfnFunction;
    lambdaResource.cfnOptions.metadata = {
      cfn_nag: {
        rules_to_suppress: [
          {
            id: 'W58',
            reason: 'Lambda function has CloudWatch Logs permissions via attached policy.',
          },
          {
            id: 'W89',
            reason: 'This Lambda function does not need to access VPC resources.',
          },
          {
            id: 'W92',
            reason: 'Reserved concurrency is not required for this use case.',
          },
        ],
      },
    };

    addCfnGuardSuppression(this.apiLambda, 'LAMBDA_INSIDE_VPC');
    addCfnGuardSuppression(this.apiLambda, 'LAMBDA_CONCURRENCY_CHECK');

    const apiLogGroup = new logs.LogGroup(this, 'AsrApiLogGroup', {
      retention: logs.RetentionDays.TEN_YEARS,
    });

    addCfnGuardSuppression(apiLogGroup, 'CLOUDWATCH_LOG_GROUP_ENCRYPTED');

    const allowHeaders = [
      'Content-Type',
      'X-Amz-Date',
      'Authorization',
      'X-Api-Key',
      'X-Amz-Security-Token',
      'X-Amz-User-Agent',
    ];
    // Stage name is reused by the WAF rate-based rules below: AWS WAF inspects
    // the full request URI including the stage as the first path segment
    // (e.g. '/prod/controls/bulk-edit'), so scope-down path matches must be
    // built from this same value.
    const apiStageName = 'prod';
    this.api = new apigateway.RestApi(this, 'AutomatedSecurityResponseApi', {
      restApiName: `AutomatedSecurityResponseApi`,
      description: 'Automated Security Response on AWS solution APIs',
      deployOptions: {
        stageName: apiStageName,
        dataTraceEnabled: false,
        metricsEnabled: true,
        accessLogDestination: new apigateway.LogGroupLogDestination(apiLogGroup),
        accessLogFormat: apigateway.AccessLogFormat.jsonWithStandardFields(),
        // Account-wide stage throttle: a global ceiling far below the 10,000 RPS
        // API Gateway default, so a single client cannot exhaust account-level
        // capacity. This is coarse and not per-user — per-user and per-endpoint
        // limits are enforced by the WAF rate-based rules. Per-method throttling
        // is intentionally not used: every route is served by a single ANY
        // /{proxy+} method, so there is no per-route method to throttle here.
        throttlingRateLimit: config.rateLimiting.stage.rateLimit,
        throttlingBurstLimit: config.rateLimiting.stage.burstLimit,
      },
      defaultCorsPreflightOptions: {
        allowOrigins: apigateway.Cors.ALL_ORIGINS,
        allowMethods: apigateway.Cors.ALL_METHODS,
        allowCredentials: false,
        allowHeaders: allowHeaders,
      },
    });

    const authorizationOptions: any = {
      apiKeyRequired: false,
    };

    if (props.authorizer) {
      authorizationOptions.authorizationType = apigateway.AuthorizationType.COGNITO;
      authorizationOptions.authorizer = props.authorizer;
      authorizationOptions.authorizationScopes = ['asr-api/api'];
    }

    const responseHeaders = {
      'gatewayresponse.header.Access-Control-Allow-Origin': "'*'",
      'gatewayresponse.header.Access-Control-Allow-Headers':
        "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'",
      'gatewayresponse.header.Access-Control-Allow-Methods': "'GET,OPTIONS,POST,PUT,DELETE'",
    };

    const proxyResource = this.api.root.addResource('{proxy+}', {
      defaultCorsPreflightOptions: {
        allowOrigins: apigateway.Cors.ALL_ORIGINS,
        allowMethods: apigateway.Cors.ALL_METHODS,
        allowCredentials: false,
        allowHeaders: allowHeaders,
      },
    });

    const lambdaIntegration = new apigateway.LambdaIntegration(this.apiLambda, {});
    proxyResource.addMethod('ANY', lambdaIntegration, authorizationOptions);

    new apigateway.GatewayResponse(this, 'CORSResponse4xx', {
      restApi: this.api,
      type: apigateway.ResponseType.DEFAULT_4XX,
      responseHeaders: responseHeaders,
    });

    new apigateway.GatewayResponse(this, 'CORSResponse5xx', {
      restApi: this.api,
      type: apigateway.ResponseType.DEFAULT_5XX,
      responseHeaders: responseHeaders,
    });

    const apiResource = this.api.node.findChild('Resource') as apigateway.CfnRestApi;
    apiResource.cfnOptions.metadata = {
      cfn_nag: {
        rules_to_suppress: [
          {
            id: 'W59',
            reason: 'API Gateway is configured with CloudWatch logging and X-Ray tracing.',
          },
        ],
      },
    };

    addCfnGuardSuppression(this.api.deploymentStage, 'API_GW_CACHE_ENABLED_AND_ENCRYPTED');

    // ── API rate limiting (WAF rate-based rules) ─────────────────────────────
    const rateLimitRules = buildRateLimitRules(config.rateLimiting.waf, apiStageName, props.resourceNamePrefix);

    // WAF Web ACL
    const cfnWebACL = new wafv2.CfnWebACL(this, 'WebACL', {
      name: `${props.resourceNamePrefix}-ASR-WebACL`,
      scope: 'REGIONAL',
      defaultAction: { allow: {} },
      description: 'WAF for Automated Security Response on AWS solution',
      // Body returned by the rate-based rules with HTTP 429 (see buildRateLimitRules).
      customResponseBodies: {
        [RATE_LIMIT_RESPONSE_BODY_KEY]: {
          contentType: 'APPLICATION_JSON',
          content: JSON.stringify({ message: 'Too many requests. Please retry later.' }),
        },
      },
      visibilityConfig: {
        cloudWatchMetricsEnabled: true,
        metricName: `${props.resourceNamePrefix}ASRWebAclMetrics`,
        sampledRequestsEnabled: true,
      },
      rules: [
        managedRuleGroupRule(
          'AWSManagedRulesBotControlRuleSet',
          'AWS',
          1,
          M2M_COUNT_RULE_OVERRIDES.AWSManagedRulesBotControlRuleSet.map((name) => ({
            name,
            actionToUse: { count: {} },
          })),
        ),
        managedRuleGroupRule('AWSManagedRulesKnownBadInputsRuleSet', 'AWS', 2),
        managedRuleGroupRule('AWSManagedRulesCommonRuleSet', 'AWS', 3),
        managedRuleGroupRule('AWSManagedRulesAnonymousIpList', 'AWS', 4),
        managedRuleGroupRule('AWSManagedRulesAmazonIpReputationList', 'AWS', 5),
        managedRuleGroupRule('AWSManagedRulesAdminProtectionRuleSet', 'AWS', 6),
        managedRuleGroupRule('AWSManagedRulesSQLiRuleSet', 'AWS', 7),
        ...rateLimitRules,
      ],
    });

    new wafv2.CfnWebACLAssociation(this, 'WebACLAssociation', {
      resourceArn: this.api.deploymentStage.stageArn,
      webAclArn: cfnWebACL.attrArn,
    });
  }
}
