// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { CloudFormationCustomResourceEvent, Context } from 'aws-lambda';
import { ASRS3Client } from '../clients/ASRS3Client';
import { Logger } from '@aws-lambda-powertools/logger';
import { FAILED, send, SUCCESS } from './cfnResponse';

export interface WebUIConfig {
  SrcBucket: string;
  SrcPath: string;
  WebUIBucket: string;
  awsExports: Record<string, any>;
}

export interface WebUIManifest {
  files: string[];
}

const logger = new Logger({
  serviceName: 'DeployWebUI',
  logLevel: (process.env.LOG_LEVEL as any) || 'INFO',
});

export async function lambdaHandler(event: CloudFormationCustomResourceEvent, context: Context): Promise<void> {
  logger.info('Event:', { event });

  try {
    if (event.RequestType === 'Create' || event.RequestType === 'Update') {
      const deployer = new WebUIDeployer();
      await deployer.deploy();
    }
    logger.info('SUCCESS:', { event });
    await send(event, context, SUCCESS, { Message: 'WebUI successfully deployed' });
  } catch (error) {
    logger.error('An error occurred:', { error });
    await send(event, context, FAILED, { Message: 'An error occurred' });
  }
}

export class WebUIDeployer {
  private logger: Logger;
  private s3: ASRS3Client;

  constructor() {
    this.logger = new Logger({
      serviceName: 'WebUIDeployer',
      logLevel: (process.env.LOG_LEVEL as any) || 'INFO',
    });
    this.s3 = new ASRS3Client();
  }

  async deploy(): Promise<void> {
    /**
     * To deploy the solution console:
     * - copy all files from source bucket that begin with /solution-name/version/webui to target bucket
     * - create aws-exports.json in target bucket
     * As opposed to service-type frontend projects, the configuration is not known at build time
     * because URLs and IDs only get created at deploy time.
     * For that reason, aws-exports.json cannot be included in the build
     * but has to be created dynamically at deploy time.
     */
    const configString = process.env.CONFIG;
    if (!configString) {
      throw new Error('CONFIG environment variable is required');
    }

    const config: WebUIConfig = JSON.parse(configString);
    this.logger.info('Config:', { config });

    await this.copyUIFilesToConsoleBucket(config);
    await this.createConfigFile(config);
  }

  private async createConfigFile(config: WebUIConfig): Promise<void> {
    this.logger.info('Reading awsExports');
    const exports = config.awsExports;
    this.logger.info('AWS Exports:', { exports });

    const webuiBucket = config.WebUIBucket;
    this.logger.info(`Creating aws-exports.json in ${webuiBucket}`);
    await this.s3.writeJsonAsFile(webuiBucket, 'aws-exports.json', exports);
  }

  private async copyUIFilesToConsoleBucket(config: WebUIConfig): Promise<void> {
    const webuiBucketName = config.WebUIBucket;
    const sourceBucketName = config.SrcBucket;
    const keyPrefix = config.SrcPath;

    // the webui-manifest.json has to be generated by build.sh. it lists all files of the bundled frontend
    const manifestFile = keyPrefix + 'webui-manifest.json';
    this.logger.info(`Reading ${manifestFile} from ${sourceBucketName}`);

    const configJson = (await this.s3.readJsonFile(sourceBucketName, manifestFile)) as WebUIManifest;
    const webUIFileNames = configJson.files;

    this.logger.info(`Deploying files from bucket ${sourceBucketName}, path ${keyPrefix} to ${webuiBucketName}`);

    for (const fileName of webUIFileNames) {
      await this.s3.copyFile(sourceBucketName, webuiBucketName, keyPrefix, '', fileName);
    }

    this.logger.info('WebUI assets copied successfully');
  }
}
