// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { Amplify, ResourcesConfig } from 'aws-amplify';
import { cognitoUserPoolsTokenProvider } from 'aws-amplify/auth/cognito';
import { sessionStorage } from 'aws-amplify/utils';
import React from 'react';
import ReactDOM from 'react-dom/client';
import { Provider } from 'react-redux';
import { BrowserRouter } from 'react-router-dom';
import { AppComponent } from './App.tsx';
import { ConfigContextProvider } from './contexts/ConfigContext.tsx';
import { NotificationContextProvider } from './contexts/NotificationContext.tsx';
import { UserContextProvider } from './contexts/UserContext.tsx';
import { startMockServer } from './mocks/browser.ts';
import { setupStore } from './store/store.ts';
import './styles.css';

/**
 * Read the configuration .json file that was generated by the custom resource during deployment.
 * If running in development mode, also enable mock-service-worker to intercept defined http requests.
 */
const getRuntimeConfig = async () => {
  let runtimeConfig: any = {};
  try {
    const response = await fetch('/aws-exports.json');
    runtimeConfig = await response.json();
  } catch (e) {
    console.log(e);
  }

  if (process.env.NODE_ENV === 'development') await startMockServer(runtimeConfig.API?.endpoints?.[0]?.endpoint);

  return runtimeConfig;
};

getRuntimeConfig().then((json) => {
  const awsconfig: ResourcesConfig = {
    Auth: {
      Cognito: {
        userPoolId: json.Auth?.userPoolId,
        userPoolClientId: json.Auth?.userPoolWebClientId,
        loginWith: {
          oauth: {
            domain: json.Auth?.oauth?.domain,
            redirectSignIn: [json.Auth?.oauth?.redirectSignIn],
            redirectSignOut: [json.Auth?.oauth?.redirectSignOut],
            responseType: 'code',
            scopes: json.Auth?.oauth?.scope,
            providers: [],
          },
        },
      },
    },
    API: {
      REST: {
        'solution-api': {
          endpoint: json.API?.endpoints?.[0]?.endpoint,
        },
      },
    },
  };
  console.log(awsconfig);
  Amplify.configure(awsconfig);
  
  // Configure session storage for auth tokens
  cognitoUserPoolsTokenProvider.setKeyValueStorage(sessionStorage);

  const store = setupStore();
  const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);

  // if auth is not configured, render the frontend without authentication for local UI development.
  // will not be able to connect to any backend / API.
  const isAuthConfigured = !!awsconfig.Auth?.Cognito.userPoolId;

  // Extract configuration for the app
  const appConfig = {
    ticketingEnabled: json.ticketingEnabled === 'true'
  };

  root.render(
    <React.StrictMode>
      <BrowserRouter>
        <Provider store={store}>
          <ConfigContextProvider config={appConfig}>
            <NotificationContextProvider>
              {isAuthConfigured ? (
                <UserContextProvider>
                  <AppComponent />
                </UserContextProvider>
              ) : (
                <AppComponent />
              )}
            </NotificationContextProvider>
          </ConfigContextProvider>
        </Provider>
      </BrowserRouter>
    </React.StrictMode>,
  );
});
