#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate skeleton files for a new ASR remediation into the workspace.

Writes three skeleton files under the ASR source tree (idempotent — never
overwrites existing files):
  source/remediation_runbooks/<ns>_<n>/<ns>_<n>.py
  source/remediation_runbooks/<ns>_<n>/<ns>_<n>.yaml
  source/playbooks/SC/ssmdocs/SC_<ControlId>.ts

The control `.ts` is only meaningful for an in-repo built-in; it is written in
both modes and can be ignored (or deleted) on the Custom Runbook path.

Usage:
    generate_runbook.py --control-id S3.9 --description "..." [--service-name s3]
                        [--workspace-root <path>] [--mode custom|builtin]

Without `--workspace-root`, the files go into the solution checkout: the one
`ASR_WORKSPACE_ROOT` names, else the nearest at or above the current directory. A
directory that is not a checkout is refused. An explicit `--workspace-root` is
written into as given, so a scratch directory such as `.tmp/<ControlId>` works.

`--mode` selects the runbook's parameter block (custom declares `Finding`; builtin
does not, as a child document) and the `nextSteps` the report suggests.

Exit codes: 0 = files created (or already existed), 2 = usage/error.
Prints a JSON report ({mode, controlId, created, nextSteps}) to stdout.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Literal, TypedDict

from solution_checkout import CheckoutNotFoundError, resolve_checkout_root

# The two authoring paths, spelled as a type so a typo cannot reach `next_steps`
# and silently take the Custom Runbook branch. Mirrors the `--mode` choices.
AuthoringMode = Literal["custom", "builtin"]


class GenerateResult(TypedDict):
    """The JSON report `generate` returns, and the CLI prints to stdout.

    Spelled out so callers read fields instead of indexing into `Any`: the keys
    are fixed and their types are known, and `mode` in particular is the same
    `Literal` the CLI parsed rather than a bare `str`.
    """

    mode: AuthoringMode
    controlId: str
    created: list[str]
    nextSteps: list[str]


def render_remediation_py(control_id: str, description: str) -> str:
    return "\n".join(
        [
            "# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.",
            "# SPDX-License-Identifier: Apache-2.0",
            "",
            f'"""Remediation script for {control_id}.',
            "",
            description,
            '"""',
            "",
            "import boto3",
            "",
            "",
            "def connect_to_service(service, boto_config, region):",
            "    return boto3.client(service, region_name=region, config=boto_config)",
            "",
            "",
            "def remediate(event, context):",
            '    """TODO: implement remediation logic."""',
            '    raise NotImplementedError("Implement remediation for this control")',
            "",
        ]
    )


def render_remediation_yaml(
    control_id: str, description: str, *, mode: AuthoringMode = "custom"
) -> str:
    """The runbook skeleton, shaped for how the document will be invoked.

    A Custom Runbook is started by the Orchestrator directly and receives exactly
    `AutomationAssumeRole` and `Finding`, so it must declare both. A built-in
    remediation is a *child* document behind a control wrapper that has already
    parsed the finding and passes plain values (`BucketName`, `TopicArn`, ...);
    none of the shipped child documents declares `Finding`, and a required one
    would make the wrapper's call fail. Its parameters are left for the author.
    """
    indented = description.replace("\n", "\n  ")
    return "\n".join(
        [
            f"# Remediation runbook skeleton for {control_id}",
            "# Generated by asr-remediation-authoring skill. Review and complete before committing.",
            'schemaVersion: "0.3"',
            # `|`, not `|-`: generation-instructions.md requires a literal block
            # and every runbook in the repository uses this form, so the scaffold
            # must not hand the author a shape the rules then reject.
            "description: |",
            f"  {indented}",
            'assumeRole: "{{ AutomationAssumeRole }}"',
            "parameters:",
            "  AutomationAssumeRole:",
            "    type: String",
            "    description: (Required) IAM role for SSM Automation.",
            "    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\\d{12}:role/[\\w+=,.@-]+$'",
            *(
                [
                    "  Finding:",
                    "    type: String",
                    "    description: (Required) ASFF finding passed by the ASR Orchestrator as JSON.",
                    "    allowedPattern: '^\\{[\\s\\S]*\\}$'",
                ]
                if mode == "custom"
                else [
                    "  # Add the values the control wrapper passes (for example BucketName).",
                    "  # A child document does not receive Finding.",
                ]
            ),
            "mainSteps: []",
            "",
        ]
    )


def render_control_ts(control_id: str, description: str, service_name: str) -> str:
    # `S3.9` is not a legal TypeScript identifier, so the export name replaces
    # every non-alphanumeric character rather than the dot alone.
    typescript_identifier = "".join(c if c.isalnum() else "_" for c in control_id)
    return "\n".join(
        [
            "// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.",
            "// SPDX-License-Identifier: Apache-2.0",
            "",
            f"// TODO: implement the control runbook for {control_id}.",
            f"// {description}",
            "",
            f"export const {typescript_identifier} = {{",
            f"  controlId: '{control_id}',",
            f"  serviceName: '{service_name}',",
            "};",
            "",
        ]
    )


def next_steps(mode: AuthoringMode, yaml_path: Path) -> list[str]:
    """Follow-up commands, which differ by authoring path.

    A run-time Custom Runbook never touches the repo build; an in-repo built-in
    does, and its commands are the repo's own npm scripts.

    The validate command carries the mode. `validate_runbook.py` defaults to
    `custom`, which enforces the Orchestrator's two-parameter contract — a rule a
    built-in child document is exempt from, because it runs behind a wrapper that
    has already parsed the finding. Emitting the bare command for a built-in told
    the author to chase `[orchestrator-parameters]` errors against a legitimately
    shaped document, and the only way to satisfy them would have been to declare a
    `Finding` parameter the built-in never receives.
    """
    authored_steps = [
        "Author the mainSteps — the scaffold ships `mainSteps: []` and will not validate.",
    ]
    if mode == "builtin":
        return authored_steps + [
            f"Run `python3 scripts/validate_runbook.py {yaml_path} --mode builtin` "
            "until it reports valid.",
            "Register the control per references/builtin-remediation.md "
            "(control_runbooks-construct.ts, sc_remediations.ts, versionAdded, metrics).",
            "Run `cd source && npm run build` to compile, then `npm run check` before committing.",
        ]
    return authored_steps + [
        f"Run `python3 scripts/validate_runbook.py {yaml_path}` until it reports valid.",
        "Create the exact remediation role and least-privilege policy from the "
        "authored API calls, following references/remediation-iam.md.",
        "Test it with `python3 scripts/test_runbook.py --script <handler.py> "
        "--assume-role <role-arn>`; the executeScript sandbox requires role "
        "credentials for AWS API calls.",
        "Deploy and execute per references/authoring-loop.md sections 5-7. "
        "Do not run deployment/dev/deploy-dev.sh for a single remediation.",
    ]


def generate(
    control_id: str,
    description: str,
    *,
    service_name: str,
    workspace_root: Path,
    mode: AuthoringMode = "custom",
) -> GenerateResult:
    """Write the skeleton files for `control_id` under `workspace_root`.

    `service_name` onward are keyword-only: it and `description` are both plain
    strings, so a positional call could swap them and still type-check — and the
    result would be a runbook whose description reads "s3" and whose control `.ts`
    claims a service named after the remediation. The two that stay positional
    read unambiguously at the call site.
    """
    if "." not in control_id:
        raise ValueError(f'invalid control_id "{control_id}"; expected e.g. "S3.1"')
    namespace, number = control_id.split(".", 1)
    if not namespace or not number:
        raise ValueError(f'invalid control_id "{control_id}"; expected e.g. "S3.1"')

    remediation_dir = (
        workspace_root / "source" / "remediation_runbooks" / f"{namespace}_{number}"
    )
    control_ts = (
        workspace_root
        / "source"
        / "playbooks"
        / "SC"
        / "ssmdocs"
        / f"SC_{control_id}.ts"
    )
    remediation_dir.mkdir(parents=True, exist_ok=True)

    py_path = remediation_dir / f"{namespace}_{number}.py"
    yaml_path = remediation_dir / f"{namespace}_{number}.yaml"

    created: list[str] = []
    if not py_path.exists():
        py_path.write_text(
            render_remediation_py(control_id, description), encoding="utf-8"
        )
        created.append(str(py_path))
    if not yaml_path.exists():
        yaml_path.write_text(
            render_remediation_yaml(control_id, description, mode=mode),
            encoding="utf-8",
        )
        created.append(str(yaml_path))
    if not control_ts.exists():
        control_ts.parent.mkdir(parents=True, exist_ok=True)
        control_ts.write_text(
            render_control_ts(control_id, description, service_name), encoding="utf-8"
        )
        created.append(str(control_ts))

    return {
        "mode": mode,
        "controlId": control_id,
        "created": created,
        "nextSteps": next_steps(mode, yaml_path),
    }


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="generate_runbook.py")
    parser.add_argument("--control-id", dest="control_id", required=True)
    parser.add_argument("--description", required=True)
    parser.add_argument("--service-name", dest="service_name", default="")
    parser.add_argument(
        "--workspace-root",
        dest="workspace_root",
        default=None,
        help="Directory to write into (default: the solution checkout).",
    )
    parser.add_argument(
        "--mode",
        choices=["custom", "builtin"],
        default="custom",
        help=(
            "custom: a run-time Custom Runbook deployed into one account (default). "
            "builtin: a remediation added to the solution source tree."
        ),
    )
    try:
        args = parser.parse_args(argv[1:])
    except SystemExit as error:
        return error.code if isinstance(error.code, int) else 2
    # argparse `choices` constrains this at run time but types it `str`, so the
    # narrowing is written out rather than cast.
    mode: AuthoringMode = "builtin" if args.mode == "builtin" else "custom"
    try:
        # Defaulting to the current directory wrote a stray `source/` tree into
        # whatever directory the command ran from, such as `source/source/…`.
        workspace_root = (
            Path(args.workspace_root)
            if args.workspace_root is not None
            else resolve_checkout_root([Path.cwd()])
        )
    except CheckoutNotFoundError as err:
        print(f"generate_runbook: {err}", file=sys.stderr)
        return 2
    try:
        result = generate(
            args.control_id,
            args.description,
            service_name=args.service_name,
            workspace_root=workspace_root,
            mode=mode,
        )
    except ValueError as err:
        print(f"generate_runbook: {err}", file=sys.stderr)
        return 2
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
