name: CDK Nag Test

on:
  push:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  cdk-nag:
    name: CDK Nag Check
    if: ${{ (github.repository_owner != 'aws-solutions' && github.event_name == 'push') || (github.repository_owner == 'aws-solutions' && github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd source
          npm ci
          cd solution_deploy
          npx cdk synth
          cd ../playbooks/AFSBP
          npx cdk synth
          cd ../CIS120
          npx cdk synth
          cd ../CIS140
          npx cdk synth
          cd ../NEWPLAYBOOK
          npx cdk synth
          cd ../PCI321
          npx cdk synth
          cd ../SC
          npx cdk synth
