name: CDK Deploy
on:
  pull_request:
    branches:
    - main
    paths:
    - "bootstrap/**"

jobs:
  update-templates:
    name: Update ASR CF templates and upload to S3
    runs-on: ["self-hosted", "asr", "temporary"]
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install Python dependencies and CDK
      run: |
        python -m pip install --upgrade pip
        # install your Python dependencies here
        npm install -g aws-cdk   

    - name: Compile ASR CDK project
      run: "cd bootstrap \nnpm i\npwd\n#magic___^_^___line\n"

    - name: Run CDK Diff
      id: diff
      run: "cd bootstrap\nnpm ci\ncdk diff --context regions=${{ secrets.REGIONS }} --context accounts=${{ secrets.ACCOUNTS }} --context bucketid=${{ secrets.BUCKET_ID }} --context payerid=${{ secrets.PAYER_ID }} | tee /tmp/diff.txt\necho 'diff<<EOF' >> $GITHUB_OUTPUT\necho \"$(cat /tmp/diff.txt)\" >> $GITHUB_OUTPUT\necho 'EOF' >> $GITHUB_OUTPUT \n#magic___^_^___line\n"
    
    - name: Update Pull Request Success
      if: steps.diff.outcome == 'success'
      uses: actions/github-script@v6
      env:
        DIFF: "${{ steps.diff.outputs.diff}}"
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        script: "const output = `Ran CDK Diff \n#magic___^_^___line\n${process.env.DIFF}  \n#magic___^_^___line\n---\n#magic___^_^___line\n  - :arrow_forward:  Logs for this run can be found here ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n`;\n  #magic___^_^___line\ngithub.rest.issues.createComment({\n  issue_number: context.issue.number,\n  owner: context.repo.owner,\n  repo: context.repo.repo,\n  body: output\n}) \n  #magic___^_^___line\n"
    
    - name: Update Pull Request Failure
      if: steps.diff.outcome == 'failure'
      uses: actions/github-script@v6
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        script: |
          const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
          const output = `
          **Failed:** CDK Diff failed with an error.
          - :sos: The detail of the failure can be found here <a href="${url}">here</a>
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })