# Workflow that runs unit test
name: Unit Test

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  unittest:
    name: Unit Test Check
    if: ${{ (github.repository_owner != 'aws-solutions' && github.event_name == 'push') || (github.repository_owner == 'aws-solutions' && github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd source
          npm ci
          cd ../deployment
          DEBUG=true ./run-unit-tests.sh
